################ English language ##################
[en]
label = "En"
locale = "en-us"
contentDir = "content/english"
weight = 1

################ Spanish language ##################
[es]
label = "Es"
locale = "es-co"
contentDir = "content/spanish"
weight = 2
