############# Spanish navigation ##############

# main menu
[[main]]
name = "Inicio"
url = "/"
weight = 1

[[main]]
name = "Sobre mí"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3

[[main]]
name = "Publicaciones"
url = "/publications"
weight = 4

[[main]]
name = "Servicios"
url = "/services"
weight = 5

[[main]]
name = "Contacto"
url = "/contact"
weight = 6


# footer menu
[[footer]]
name = "Sobre mí"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

[[footer]]
name = "Publicaciones"
url = "/publications"
weight = 3

[[footer]]
name = "Servicios"
url = "/services"
weight = 4

[[footer]]
name = "Contacto"
url = "/contact"
weight = 5

[[footer]]
name = "Privacidad"
url = "/privacy"
weight = 6
